services:
  typetype-token:
    image: ghcr.io/priveetee/typetype-token:latest
    ports:
      - "8081:8081"
    restart: unless-stopped
    init: true
    ipc: host
    environment:
      - NODE_ENV=production
