import { describe, expect, it, mock } from "bun:test";
import type { SubtitleTrack } from "../src/subtitles.ts";

const VISITOR_DATA = "visitor-data-test-123";
const INTEGRITY_TOKEN = "integrity-token-test-xyz";
const PO_TOKEN = `pot-${VISITOR_DATA}`;

mock.module("../src/botguard-page.ts", () => ({
	executeBotGuard: mock(async (): Promise<string> => "botguard-response-test"),
	mintPoToken: mock(async (_token: string, id: string): Promise<string> => `pot-${id}`),
	resetBotGuardPage: mock(async (): Promise<void> => undefined),
}));

mock.module("../src/token-service.ts", () => ({
	getOrRefreshSession: mock(async () => ({
		visitorData: VISITOR_DATA,
		poToken: PO_TOKEN,
		integrityToken: INTEGRITY_TOKEN,
		expiresAt: Date.now() + 3600_000,
	})),
	fetchPoToken: mock(async (videoId: string) => ({
		poToken: PO_TOKEN,
		visitorData: VISITOR_DATA,
		streamingPot: `pot-${videoId}`,
	})),
}));

const frTrack = {
	baseUrl: "https://www.youtube.com/api/timedtext?lang=fr",
	name: { simpleText: "French" },
	languageCode: "fr",
};

const asrTrack = {
	baseUrl: "https://www.youtube.com/api/timedtext?lang=en",
	name: { simpleText: "English (auto-generated)" },
	languageCode: "en",
	kind: "asr",
};

const mockFetchCaptionTracks = mock(async () => [frTrack, asrTrack]);

mock.module("../src/innertube.ts", () => ({
	fetchCaptionTracks: mockFetchCaptionTracks,
	fetchVisitorData: mock(async (): Promise<string> => VISITOR_DATA),
	fetchChallenge: mock(async () => ({})),
	fetchIntegrityToken: mock(async () => ({ integrityToken: INTEGRITY_TOKEN })),
}));

describe("fetchSubtitles", () => {
	it("maps caption tracks to SubtitleTrack shape", async () => {
		const { fetchSubtitles } = await import("../src/subtitles.ts");
		const result: SubtitleTrack[] = await fetchSubtitles("dQw4w9WgXcQ");

		expect(result).toHaveLength(2);

		expect(result[0]).toEqual({
			url: "https://www.youtube.com/api/timedtext?lang=fr",
			mimeType: "application/ttml+xml",
			languageTag: "fr",
			displayLanguageName: "French",
			isAutoGenerated: false,
		});

		expect(result[1]).toEqual({
			url: "https://www.youtube.com/api/timedtext?lang=en",
			mimeType: "application/ttml+xml",
			languageTag: "en",
			displayLanguageName: "English (auto-generated)",
			isAutoGenerated: true,
		});
	});

	it("returns empty array when no caption tracks", async () => {
		mockFetchCaptionTracks.mockImplementation(async () => []);
		const { fetchSubtitles } = await import("../src/subtitles.ts");
		const result = await fetchSubtitles("no-captions-video");
		expect(result).toEqual([]);
	});

	it("skips tracks with missing baseUrl or languageCode", async () => {
		mockFetchCaptionTracks.mockImplementation(async () => [
			{ name: { simpleText: "Bad" } },
			frTrack,
		]);
		const { fetchSubtitles } = await import("../src/subtitles.ts");
		const result = await fetchSubtitles("partial-video");
		expect(result).toHaveLength(1);
		expect(result[0].languageTag).toBe("fr");
	});
});
